//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Inputs/Inputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Inputs"",
    ""maps"": [
        {
            ""name"": ""Standard"",
            ""id"": ""e2fab303-78fb-42d2-8a75-37992f319caa"",
            ""actions"": [
                {
                    ""name"": ""Jump"",
                    ""type"": ""Value"",
                    ""id"": ""2455aa88-56f5-4c30-b5a2-c53798406b7c"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""567ee66c-e9f7-4a47-9833-765f455d9f34"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MoveCamera"",
                    ""type"": ""Value"",
                    ""id"": ""e4b6f3c3-bd13-4193-b056-816061fd98e1"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SlowMo"",
                    ""type"": ""Value"",
                    ""id"": ""1c4161ad-65be-4e54-a3ee-2b228e3004c4"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Spawn1"",
                    ""type"": ""Button"",
                    ""id"": ""93fb6088-cb8e-4e7b-8551-e6d18cac102a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Spawn2"",
                    ""type"": ""Button"",
                    ""id"": ""79374bd9-47c7-4321-8105-607729bcf057"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Spawn3"",
                    ""type"": ""Button"",
                    ""id"": ""ce58c8a0-9d92-453d-a314-572081238faf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Spawn4"",
                    ""type"": ""Button"",
                    ""id"": ""58aeac49-d54c-43b8-a0a8-7ca0aad54d8b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Spawn5"",
                    ""type"": ""Button"",
                    ""id"": ""32e9222e-1084-4186-a703-ba866bde2145"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Spawn6"",
                    ""type"": ""Button"",
                    ""id"": ""37c50a89-0a30-46d7-b3d0-6856a3a1abe6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Spawn7"",
                    ""type"": ""Button"",
                    ""id"": ""ee8afc45-2f25-4c0e-9889-95c8294947fe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Spawn8"",
                    ""type"": ""Button"",
                    ""id"": ""3b367cde-27f9-43ff-88fa-f462c0c06d37"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Respawn"",
                    ""type"": ""Button"",
                    ""id"": ""b9705e59-42cc-4dd1-8097-2ee27a75adfc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""469cfac9-cc73-4082-b81d-c389d1ba2567"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d9c5f987-1c7d-423d-8aa3-881cbf4afaf7"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5b62d4a9-ed6a-4e1f-a355-bad52ec50f3e"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""ab2e0825-0b46-4809-aea0-13464a86f7ff"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""daf58bd7-ba78-476f-9fa5-ba769ea755d2"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""cd2bd354-b014-48a8-8e27-34001215dfd8"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""481a1540-db6e-42d2-933e-8dfe4d8272fd"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""36724feb-4d79-415b-950e-baf211b6b110"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""1ce81031-b316-4700-b4c3-9b28ae4aed0f"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""InvertVector2(invertX=false,invertY=false)"",
                    ""groups"": """",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9ba01248-d707-40bc-bd5c-4917fb206256"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6ec03f1a-3067-4e93-a6b8-eca45d0c96f8"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlowMo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ad93f97e-3eee-4503-8e21-5b475ae08ba5"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spawn1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0a6cd500-8007-4c0f-87d6-583ca5216589"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spawn2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4dcca33f-170c-4625-8a4a-165d5e39e503"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spawn3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da879bc6-0526-4d64-bece-43dcb8106341"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spawn4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9453eb4e-776e-49b4-847c-c53061e96634"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spawn5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f8b0707-7117-4bab-924e-f0e7cff3b961"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spawn6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d91b4b71-9260-4131-82f2-fed9f46a81a8"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spawn7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ce5179fa-63e7-44cb-a6bd-75c4d523f44a"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spawn8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86613f82-d5f0-47df-973d-1ef15704c0d4"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Respawn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1463ea73-87ce-481e-8698-61b6bbe8b755"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Respawn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Standard
        m_Standard = asset.FindActionMap("Standard", throwIfNotFound: true);
        m_Standard_Jump = m_Standard.FindAction("Jump", throwIfNotFound: true);
        m_Standard_Move = m_Standard.FindAction("Move", throwIfNotFound: true);
        m_Standard_MoveCamera = m_Standard.FindAction("MoveCamera", throwIfNotFound: true);
        m_Standard_SlowMo = m_Standard.FindAction("SlowMo", throwIfNotFound: true);
        m_Standard_Spawn1 = m_Standard.FindAction("Spawn1", throwIfNotFound: true);
        m_Standard_Spawn2 = m_Standard.FindAction("Spawn2", throwIfNotFound: true);
        m_Standard_Spawn3 = m_Standard.FindAction("Spawn3", throwIfNotFound: true);
        m_Standard_Spawn4 = m_Standard.FindAction("Spawn4", throwIfNotFound: true);
        m_Standard_Spawn5 = m_Standard.FindAction("Spawn5", throwIfNotFound: true);
        m_Standard_Spawn6 = m_Standard.FindAction("Spawn6", throwIfNotFound: true);
        m_Standard_Spawn7 = m_Standard.FindAction("Spawn7", throwIfNotFound: true);
        m_Standard_Spawn8 = m_Standard.FindAction("Spawn8", throwIfNotFound: true);
        m_Standard_Respawn = m_Standard.FindAction("Respawn", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Standard
    private readonly InputActionMap m_Standard;
    private List<IStandardActions> m_StandardActionsCallbackInterfaces = new List<IStandardActions>();
    private readonly InputAction m_Standard_Jump;
    private readonly InputAction m_Standard_Move;
    private readonly InputAction m_Standard_MoveCamera;
    private readonly InputAction m_Standard_SlowMo;
    private readonly InputAction m_Standard_Spawn1;
    private readonly InputAction m_Standard_Spawn2;
    private readonly InputAction m_Standard_Spawn3;
    private readonly InputAction m_Standard_Spawn4;
    private readonly InputAction m_Standard_Spawn5;
    private readonly InputAction m_Standard_Spawn6;
    private readonly InputAction m_Standard_Spawn7;
    private readonly InputAction m_Standard_Spawn8;
    private readonly InputAction m_Standard_Respawn;
    public struct StandardActions
    {
        private @PlayerInputs m_Wrapper;
        public StandardActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Jump => m_Wrapper.m_Standard_Jump;
        public InputAction @Move => m_Wrapper.m_Standard_Move;
        public InputAction @MoveCamera => m_Wrapper.m_Standard_MoveCamera;
        public InputAction @SlowMo => m_Wrapper.m_Standard_SlowMo;
        public InputAction @Spawn1 => m_Wrapper.m_Standard_Spawn1;
        public InputAction @Spawn2 => m_Wrapper.m_Standard_Spawn2;
        public InputAction @Spawn3 => m_Wrapper.m_Standard_Spawn3;
        public InputAction @Spawn4 => m_Wrapper.m_Standard_Spawn4;
        public InputAction @Spawn5 => m_Wrapper.m_Standard_Spawn5;
        public InputAction @Spawn6 => m_Wrapper.m_Standard_Spawn6;
        public InputAction @Spawn7 => m_Wrapper.m_Standard_Spawn7;
        public InputAction @Spawn8 => m_Wrapper.m_Standard_Spawn8;
        public InputAction @Respawn => m_Wrapper.m_Standard_Respawn;
        public InputActionMap Get() { return m_Wrapper.m_Standard; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(StandardActions set) { return set.Get(); }
        public void AddCallbacks(IStandardActions instance)
        {
            if (instance == null || m_Wrapper.m_StandardActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_StandardActionsCallbackInterfaces.Add(instance);
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @MoveCamera.started += instance.OnMoveCamera;
            @MoveCamera.performed += instance.OnMoveCamera;
            @MoveCamera.canceled += instance.OnMoveCamera;
            @SlowMo.started += instance.OnSlowMo;
            @SlowMo.performed += instance.OnSlowMo;
            @SlowMo.canceled += instance.OnSlowMo;
            @Spawn1.started += instance.OnSpawn1;
            @Spawn1.performed += instance.OnSpawn1;
            @Spawn1.canceled += instance.OnSpawn1;
            @Spawn2.started += instance.OnSpawn2;
            @Spawn2.performed += instance.OnSpawn2;
            @Spawn2.canceled += instance.OnSpawn2;
            @Spawn3.started += instance.OnSpawn3;
            @Spawn3.performed += instance.OnSpawn3;
            @Spawn3.canceled += instance.OnSpawn3;
            @Spawn4.started += instance.OnSpawn4;
            @Spawn4.performed += instance.OnSpawn4;
            @Spawn4.canceled += instance.OnSpawn4;
            @Spawn5.started += instance.OnSpawn5;
            @Spawn5.performed += instance.OnSpawn5;
            @Spawn5.canceled += instance.OnSpawn5;
            @Spawn6.started += instance.OnSpawn6;
            @Spawn6.performed += instance.OnSpawn6;
            @Spawn6.canceled += instance.OnSpawn6;
            @Spawn7.started += instance.OnSpawn7;
            @Spawn7.performed += instance.OnSpawn7;
            @Spawn7.canceled += instance.OnSpawn7;
            @Spawn8.started += instance.OnSpawn8;
            @Spawn8.performed += instance.OnSpawn8;
            @Spawn8.canceled += instance.OnSpawn8;
            @Respawn.started += instance.OnRespawn;
            @Respawn.performed += instance.OnRespawn;
            @Respawn.canceled += instance.OnRespawn;
        }

        private void UnregisterCallbacks(IStandardActions instance)
        {
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @MoveCamera.started -= instance.OnMoveCamera;
            @MoveCamera.performed -= instance.OnMoveCamera;
            @MoveCamera.canceled -= instance.OnMoveCamera;
            @SlowMo.started -= instance.OnSlowMo;
            @SlowMo.performed -= instance.OnSlowMo;
            @SlowMo.canceled -= instance.OnSlowMo;
            @Spawn1.started -= instance.OnSpawn1;
            @Spawn1.performed -= instance.OnSpawn1;
            @Spawn1.canceled -= instance.OnSpawn1;
            @Spawn2.started -= instance.OnSpawn2;
            @Spawn2.performed -= instance.OnSpawn2;
            @Spawn2.canceled -= instance.OnSpawn2;
            @Spawn3.started -= instance.OnSpawn3;
            @Spawn3.performed -= instance.OnSpawn3;
            @Spawn3.canceled -= instance.OnSpawn3;
            @Spawn4.started -= instance.OnSpawn4;
            @Spawn4.performed -= instance.OnSpawn4;
            @Spawn4.canceled -= instance.OnSpawn4;
            @Spawn5.started -= instance.OnSpawn5;
            @Spawn5.performed -= instance.OnSpawn5;
            @Spawn5.canceled -= instance.OnSpawn5;
            @Spawn6.started -= instance.OnSpawn6;
            @Spawn6.performed -= instance.OnSpawn6;
            @Spawn6.canceled -= instance.OnSpawn6;
            @Spawn7.started -= instance.OnSpawn7;
            @Spawn7.performed -= instance.OnSpawn7;
            @Spawn7.canceled -= instance.OnSpawn7;
            @Spawn8.started -= instance.OnSpawn8;
            @Spawn8.performed -= instance.OnSpawn8;
            @Spawn8.canceled -= instance.OnSpawn8;
            @Respawn.started -= instance.OnRespawn;
            @Respawn.performed -= instance.OnRespawn;
            @Respawn.canceled -= instance.OnRespawn;
        }

        public void RemoveCallbacks(IStandardActions instance)
        {
            if (m_Wrapper.m_StandardActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IStandardActions instance)
        {
            foreach (var item in m_Wrapper.m_StandardActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_StandardActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public StandardActions @Standard => new StandardActions(this);
    public interface IStandardActions
    {
        void OnJump(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnMoveCamera(InputAction.CallbackContext context);
        void OnSlowMo(InputAction.CallbackContext context);
        void OnSpawn1(InputAction.CallbackContext context);
        void OnSpawn2(InputAction.CallbackContext context);
        void OnSpawn3(InputAction.CallbackContext context);
        void OnSpawn4(InputAction.CallbackContext context);
        void OnSpawn5(InputAction.CallbackContext context);
        void OnSpawn6(InputAction.CallbackContext context);
        void OnSpawn7(InputAction.CallbackContext context);
        void OnSpawn8(InputAction.CallbackContext context);
        void OnRespawn(InputAction.CallbackContext context);
    }
}
